name: flutter_snappy_plugin
description: Flutter plugin for SNAPPY remote device communication on Windows and Linux platforms.
version: 1.0.3  # Patch update for web support
homepage: https://github.com/Red-Nerds/flutter_snappy_plugin
repository: https://github.com/Red-Nerds/flutter_snappy_plugin
issue_tracker: https://github.com/Red-Nerds/flutter_snappy_plugin/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.7
  socket_io_client: ^2.0.3+1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  plugin:
    platforms:
      windows:
        dartPluginClass: FlutterSnappyPlugin
      linux:
        dartPluginClass: FlutterSnappyPlugin
      macos:
        dartPluginClass: FlutterSnappyPlugin
      # Android will be added later